services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm/data:/data # mounts your .osrm files
    command: >
      osrm-routed --algorithm mld /data/map.osrm
